### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by rightlit** [rightlit/cycle-image-gan-rev#4]
Traceback (most recent call last):
  File "pretrain_STREAM.py", line 294, in <module>
    dataset.ixtoword, image_dir)
  File "pretrain_STREAM.py", line 102, in train
    loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered

**Comment by rightlit** [comment]
this problem occurs
because of difference between dimension of word_logits and from captions.
in following function.
t_loss = image_to_text_loss(word_logits, captions)
in pretrain_STREAM.py

so
I changed vocab_size to tokenize.vocab instead of dataset.n_words
here is my sample code.

=====================
def build_models():

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
vocab_size = len(tokenizer.vocab)
#vocab_size = 30522

#text_encoder = BERT_RNN_ENCODER(dataset.n_words, nhidden=cfg.TEXT.EMBEDDING_DIM)
#image_encoder = BERT_CNN_ENCODER_RNN_DECODER(cfg.TEXT.EMBEDDING_DIM, cfg.CNN_RNN.HIDDEN_DIM, dataset.n_words, rec_unit=cfg.RNN_TYPE)
text_encoder = BERT_RNN_ENCODER(vocab_size, nhidden=cfg.TEXT.EMBEDDING_DIM)
image_encoder = BERT_CNN_ENCODER_RNN_DECODER(cfg.TEXT.EMBEDDING_DIM, cfg.CNN_RNN.HIDDEN_DIM, vocab_size, rec_unit=cfg.RNN_TYPE)
